# Generated by Django 4.2.4 on 2023-08-18 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_card_clothesinshoppingcart_payment_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='ClothesInShoppingCart',
            new_name='ProductInShoppingCart',
        ),
    ]
