# Generated by Django 4.2.4 on 2023-08-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_customer_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='code',
        ),
    ]
