# Generated by Django 4.2.4 on 2023-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_id_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinshoppingcart',
            name='price',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
