# Generated by Django 4.2.4 on 2023-08-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_productinshoppingcart_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinshoppingcart',
            old_name='clothing',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='productinshoppingcart',
            name='price',
        ),
        migrations.AlterField(
            model_name='productinshoppingcart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
