# Generated by Django 4.2.4 on 2023-08-20 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_rename_clothing_productinshoppingcart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
        migrations.AddField(
            model_name='client',
            name='firstName',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='lastName',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='070 000 000', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
